# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=500)),
                ('currentlocation', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
            options={
                'db_table': 'equipments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipmentsavailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField()),
            ],
            options={
                'db_table': 'equipmentsavailable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'hospitals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'medicines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicinestocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'medicinestocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patientrecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=500)),
                ('diagnosis', models.CharField(max_length=500)),
                ('attatchmentlink', models.CharField(max_length=500)),
                ('createdat', models.CharField(max_length=500)),
                ('createdon', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'patientrecords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('aadhaarid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=1)),
                ('contact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('name', models.IntegerField()),
                ('timing', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'pharmacies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videorecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'videorecords',
                'managed': False,
            },
        ),
    ]
